//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInput
    {
        public int userid { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public string incomerange { get; set; }
        public string gender { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string maritalstatus { get; set; }
        public string numofchildren { get; set; }
        public string residentialstatus { get; set; }
        public string homevalue { get; set; }
        public string collegeeducation { get; set; }
    }
}
